package com.github.pitzzahh.enums;

public enum Status {
    SUCCESS,
    PRODUCT_SAVED_SUCCESSFULLY,
    ALL_PRODUCTS_SAVED_SUCCESSFULLY,
    PRICE_UPDATED_SUCCESSFULLY,
    STOCKS_UPDATED_SUCCESSFULLY,
    DISCOUNT_UPDATED_SUCCESSFULLY,
    PRODUCT_REMOVED_SUCCESSFULLY,
    SALES_SAVED_SUCCESSFULLY,
    ERROR_SAVING_PRODUCT,
    ERROR_GETTING_PRODUCT,
    ERROR_GETTING_ALL_PRODUCTS,
    ERROR_UPDATING_PRICE,
    ERROR_UPDATING_STOCKS,
    ERROR_UPDATING_DISCOUNT,
    ERROR_REMOVING_PRODUCT,
    ERROR_SAVING_SALES,
    ERROR_REMOVING_ALL_PRODUCTS,
    ERROR
}
